### ISSUE TITLE
hwe dtype inference

### ISSUE THREAD

**Issue by shy218** [pystatgen/sgkit#548]
When I run the HWE function on the simulated dataset or my own dataset, I get 

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sgkit/stats/hwe.py", line 214, in hardy_weinberg_test
    p = da.map_blocks(hardy_weinberg_p_value_vec_jit, *obs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dask/array/core.py", line 683, in map_blocks
    dtype = apply_infer_dtype(func, args, original_kwargs, "map_blocks")
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dask/array/core.py", line 408, in apply_infer_dtype
    raise ValueError(msg)
ValueError: `dtype` inference failed in `map_blocks`.

I use Dask 2021.04.0, xarray 0.17.0, sgkit 0.20a1

**Comment by eric-czech** [comment]
Please share the code you used to create the data and call the function.

**Comment by tomwhite** [comment]
Closing old issue
