### ISSUE TITLE
Issue of Dask on cluster, indicating 'moving large chunks of data'

### ISSUE THREAD

**Issue by LiangdeLI** [pystatgen/sgkit#683]
This is the issue I mentioned in Sep 16th's meeting, sorry it takes more time to recreate than expected because of a network issue. Do you have any idea what could be the cause of it?

## This is the core part of python code I run:
```
ds = sg.load_dataset("/mydata/output.zarr")
client = Client("tcp://xxx.xxx.xxx.xx:8786")
allele_freq_sgkit = sg.variant_stats(ds)['variant_allele_frequency'].values
```

## Cluster settings
I have two machine, run `dask-scheduler` at machine 0, and run `dask-worker tcp://xxx.xxx.xxx.xx:8786` at both machines. Python code is also run at machine 0.
Machine 0 has local storage mounted at /mydata, and machine 1 using nfs server mount the machine_1:/mydata to local /mydata.

## Error reported by python code
```
Traceback (most recent call last):
  File "distributed_sgkit_allele_freq.py", line 20, in <module>
    allele_freq_sgkit = sg.variant_stats(ds)['variant_allele_frequency'].values
  File "/users/Liangde/.local/lib/python3.8/site-packages/xarray/core/dataarray.py", line 651, in values
    return self.variable.values
  File "/users/Liangde/.local/lib/python3.8/site-packages/xarray/core/variable.py", line 517, in values
    return _as_array_or_item(self._data)
  File "/users/Liangde/.local/lib/python3.8/site-packages/xarray/core/variable.py", line 259, in _as_array_or_item
    data = np.asarray(data)
  File "/users/Liangde/.local/lib/python3.8/site-packages/numpy/core/_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/users/Liangde/.local/lib/python3.8/site-packages/dask/array/core.py", line 1491, in __array__
    x = self.compute()
  File "/users/Liangde/.local/lib/python3.8/site-packages/dask/base.py", line 288, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/users/Liangde/.local/lib/python3.8/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/users/Liangde/.local/lib/python3.8/site-packages/distributed/client.py", line 2689, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/users/Liangde/.local/lib/python3.8/site-packages/distributed/client.py", line 1966, in gather
    return self.sync(
  File "/users/Liangde/.local/lib/python3.8/site-packages/distributed/client.py", line 860, in sync
    return sync(
  File "/users/Liangde/.local/lib/python3.8/site-packages/distributed/utils.py", line 326, in sync
    raise exc.with_traceback(tb)
  File "/users/Liangde/.local/lib/python3.8/site-packages/distributed/utils.py", line 309, in f
    result[0] = yield future
  File "/users/Liangde/.local/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/users/Liangde/.local/lib/python3.8/site-packages/distributed/client.py", line 1831, in _gather
    raise exception.with_traceback(traceback)
distributed.scheduler.KilledWorker: ("('count_alleles-open_dataset-sum-fea93571d6393c7146f26bfb3d36799b', 478, 2, 0)", <WorkerState 'tcp://xxx.xxx.xxx.xx:45357', name: tcp://xxx.xxx.xxx.xx:45357, memory: 0, processing: 3882>)
```

## Error reported by dask scheduler
```
distributed.scheduler - INFO - Register worker <WorkerState 'tcp://xxx.xxx.xxx.xx:42537', name: tcp://xxx.xxx.xxx.xx:42537, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://xxx.xxx.xxx.xx.93:42537
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register worker <WorkerState 'tcp://xxx.xxx.xxx.xx:46347', name: tcp://xxx.xxx.xxx.xx:46347, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://xxx.xxx.xxx.xx:46347
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Receive client connection: Client-102a4320-1b3a-11ec-a853-70e422841622
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://xxx.xxx.xxx.xx:42537', name: tcp://xxx.xxx.xxx.xx:42537, memory: 322, processing: 1196>
distributed.core - INFO - Removing comms to tcp://xxx.xxx.xxx.xx:42537
distributed.scheduler - INFO - Register worker <WorkerState 'tcp://xxx.xxx.xxx.xx:34855', name: tcp://xxx.xxx.xxx.xx:34855, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://xxx.xxx.xxx.xx:34855
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://xxx.xxx.xxx.xx:46347', name: tcp://xxx.xxx.xxx.xx:46347, memory: 139, processing: 3882>
distributed.core - INFO - Removing comms to tcp://xxx.xxx.xxx.xx:46347
distributed.scheduler - INFO - Register worker <WorkerState 'tcp://1xxx.xxx.xxx.xx:45357', name: tcp://xxx.xxx.xxx.xx:45357, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://xxx.xxx.xxx.xx:45357

...... more lines of similar print out

distributed.scheduler - INFO - Task ('open_dataset-a346cfa3ffbf7ffde3179ebaa39ede32call_genotype_mask-1fd9d8968f2fc433b68bfb3423aa5b57', 533, 1, 0) marked as failed because 3 workers died while trying to run it
distributed.scheduler - INFO - Task ('open_dataset-a346cfa3ffbf7ffde3179ebaa39ede32call_genotype_mask-1fd9d8968f2fc433b68bfb3423aa5b57', 533, 2, 0) marked as failed because 3 workers died while trying to run it

...... more lines of similar print out

distributed.scheduler - INFO - Task ('count_alleles-open_dataset-sum-fea93571d6393c7146f26bfb3d36799b', 353, 0, 0) marked as failed because 3 workers died while trying to run it
distributed.scheduler - INFO - Task ('count_alleles-open_dataset-sum-fea93571d6393c7146f26bfb3d36799b', 353, 1, 0) marked as failed because 3 workers died while trying to run it

...... more lines of similar print out

distributed.scheduler - INFO - Register worker <WorkerState 'tcp://xxx.xxx.xxx.xx:44671', name: tcp://xxx.xxx.xxx.xx:44671, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://xxx.xxx.xxx.xx:44671
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Remove client Client-102a4320-1b3a-11ec-a853-70e422841622
distributed.scheduler - INFO - Close client connection: Client-102a4320-1b3a-11ec-a853-70e422841622
distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://xxx.xxx.xxx.xx:43545', name: tcp://xxx.xxx.xxx.xx:43545, memory: 0, processing: 0>
distributed.core - INFO - Removing comms to tcp://xxx.xxx.xxx.xx:43545
distributed.scheduler - INFO - Register worker <WorkerState 'tcp://xxx.xxx.xxx.xx:42603', name: tcp://xxx.xxx.xxx.xx:42603, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://xxx.xxx.xxx.xx:42603
distributed.core - INFO - Starting established connection
```

## Error reported by dask worker
It repeating like:
```
distributed.nanny - WARNING - Restarting worker
distributed.worker - INFO -       Start worker at: tcp://xxx.xxx.xxx.xx:34855
distributed.worker - INFO -          Listening to: tcp://xxx.xxx.xxx.xx:34855
distributed.worker - INFO -          dashboard at:       xxx.xxx.xxx.xx:34493
distributed.worker - INFO - Waiting to connect to:  tcp://xxx.xxx.xxx.xx:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         40
distributed.worker - INFO -                Memory:                 157.30 GiB
distributed.worker - INFO -       Local Directory: /users/Liangde/dask-worker-space/worker-r0gd2675
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:  tcp://xxx.xxx.xxx.xx:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Event loop was unresponsive in Worker for 103.26s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.nanny - INFO - Worker process 10463 was killed by signal 11
distributed.nanny - WARNING - Restarting worker
```

**Comment by LiangdeLI** [comment]
Some thoughs about this bug:
1. Signal 11 was reported, which is segmentation fault, I might not using Dask correcttly in python code. Maybe I need to reorder those three lines mentioned above?
2. 'This is often caused by long-running GIL-holding functions or moving large chunks of data.' might be a hint.

**Comment by hammer** [comment]
Hey @LiangdeLI are you able to share `output.zarr`?

**Comment by tomwhite** [comment]
Hi @LiangdeLI - a few thoughts below:

* How big is `output.zarr`?
* It's best to create the Dask `Client` as the first line of your program, otherwise there's a risk that some computations are done locally without you really knowing (I'm not sure that is the case here however).
* You could try running on a single machine first (in distributed mode still, see https://docs.dask.org/en/latest/setup/single-distributed.html) before moving to the multiple machine case. This avoids networking issues and gives you a performance baseline.
* Have you been using the Dask UI? This gives a lot of information about what the cluster is doing, see https://docs.dask.org/en/latest/diagnostics-distributed.html#dashboard
* A very useful feature is Dask's [performance reports](https://distributed.dask.org/en/latest/diagnosing-performance.html#performance-reports). This allows you to capture a workflow run, including task streams etc, as an HTML file that you can share here to help diagnose problems.
* I'm not sure how well an NFS mount is going to be for the shared filesystem. It's something to keep an eye on, and change to a distributed filesystem (e.g. HDFS) if it's a problem.

**Comment by LiangdeLI** [comment]
Hi @tomwhite Thanks for your suggestions!
1. `output.zarr` has size of 666MB.
2.  I tried creating Dask `Client` before loading the dataset, which is basically the first line. But still have the same issue.
3.  Yes, good suggestion. Even I run distributed scheduler on the single machine has the same problem.
4. I'm learning and trying to find more useful information on Dask UI.

Then some new findings:
`allele_freq_sgkit = sg.variant_stats(ds)['variant_allele_frequency'].values` is basically:
`ds = sg.variant_stats(ds)` + `allele_freq_sgkit = ds['variant_allele_frequency'].values`
and I found that run `ds = sg.variant_stats(ds)` solely won't cause any problem, it seems that quoting `ds['variant_allele_frequency'].values` leads to the problem.

**Comment by hammer** [comment]
@LiangdeLI http://xarray.pydata.org/en/stable/generated/xarray.DataArray.values.html is going to convert a large Dask array into a single NumPy array.

It might be helpful to work through the Xarray tutorial ([video](https://youtu.be/mecN-Ph_-78), [code](https://github.com/xarray-contrib/xarray-tutorial)) and the Dask internals tutorial ([video](https://youtu.be/LQrgDhN-XOo), [code](https://github.com/jrbourbeau/hacking-dask)) to get a better handle on which operations will be expensive.

**Comment by tomwhite** [comment]
Closing as this is quite old now
