### ISSUE TITLE
Packages dependency issue when installing sgkit release 0.3.0 with pip

### ISSUE THREAD

**Issue by LiangdeLI** [pystatgen/sgkit#746]
I used `pip3 install sgkit ` to install latest release.

When I just do `import sgkit as sg`, it raise errors:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/Liangde/.local/lib/python3.8/site-packages/sgkit/__init__.py", line 28, in <module>
    from .stats.hwe import hardy_weinberg_test
  File "/users/Liangde/.local/lib/python3.8/site-packages/sgkit/stats/hwe.py", line 6, in <module>
    from numpy.typing import NDArray
ImportError: cannot import name 'NDArray' from 'numpy.typing' (/users/Liangde/.local/lib/python3.8/site-packages/numpy/typing/__init__.py)
```

I realized `NDArray` may only in `numpy.typing` of numpy new release, then I upgraded `numpy` from 1.20 to 1.21, and `from numpy.typing import NDArray` works then. However, `numba` is unhappy:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/Liangde/.local/lib/python3.8/site-packages/sgkit/__init__.py", line 4, in <module>
    from .distance.api import pairwise_distance
  File "/users/Liangde/.local/lib/python3.8/site-packages/sgkit/distance/api.py", line 7, in <module>
    from sgkit.distance import metrics
  File "/users/Liangde/.local/lib/python3.8/site-packages/sgkit/distance/metrics.py", line 12, in <module>
    from numba import cuda, guvectorize, types
  File "/users/Liangde/.local/lib/python3.8/site-packages/numba/__init__.py", line 198, in <module>
    _ensure_critical_deps()
  File "/users/Liangde/.local/lib/python3.8/site-packages/numba/__init__.py", line 138, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.20 or less")
ImportError: Numba needs NumPy 1.20 or less
```

**Comment by LiangdeLI** [comment]
Thanks @tomwhite. I will install the latest from Github.
I was trying this newer version because I found the dataset would be much larger in memory than original .zarr file. I remember you once mentioned a memory bug fixed, which one it is? Would it be related to my issue here?

I have `.zarr` data for chromosome 21, with size 321 MB. After I do eager loading by: `ds = sg.load_dataset("/mydata/chr21.zarr").persist()`, where `persist()` is eager loading, and keep data in memory as Dask array format, the program then takes 14 G of memory after loading. And the peak memory usage in HWE benchmark reaches 25 G by doing this eager computing with `persist()`.

I reckon this memory usage is huge, although loaded the whole dataset into memory.

**Comment by tomwhite** [comment]
Closing this as we have had two new releases since.
