### ISSUE TITLE
Doc build is failing

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#830]
From https://github.com/pystatgen/sgkit/runs/5763700555?check_suite_focus=true:

```
Running Sphinx v4.2.0
python exec: /opt/hostedtoolcache/Python/3.8.[12](https://github.com/pystatgen/sgkit/runs/5763700555?check_suite_focus=true#step:6:12)/x64/bin/python
sys.path: ['/home/runner/work/sgkit/sgkit', '/opt/hostedtoolcache/Python/3.8.12/x64/bin', '/home/runner/work/sgkit/sgkit', '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python38.zip', '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8', '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/lib-dynload', '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages']
making output directory... done
[autosummary] generating autosummary for: about.rst, api.rst, contributing.rst, examples/gwas_tutorial.ipynb, examples/index.rst, getting_started.rst, how_do_i.rst, index.rst, user_guide.rst, vcf.rst
WARNING: [autosummary] failed to import 'sgkit.io.vcf.concat_zarrs': no module named sgkit.io.vcf.concat_zarrs
WARNING: [autosummary] failed to import 'sgkit.io.vcf.partition_into_regions': no module named sgkit.io.vcf.partition_into_regions
WARNING: [autosummary] failed to import 'sgkit.io.vcf.vcf_to_zarr': no module named sgkit.io.vcf.vcf_to_zarr
WARNING: [autosummary] failed to import 'sgkit.io.vcf.vcf_to_zarrs': no module named sgkit.io.vcf.vcf_to_zarrs
```

**Comment by tomwhite** [comment]
The underlying cause here is the following error, that I get with cyvcf2 version 0.30.15, but not with 0.30.14:

```python
>>> from sgkit.io.vcf import vcf_to_zarr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tom/workspace/sgkit/sgkit/io/vcf/__init__.py", line 4, in <module>
    from .vcf_partition import partition_into_regions
  File "/Users/tom/workspace/sgkit/sgkit/io/vcf/vcf_partition.py", line 6, in <module>
    from cyvcf2 import VCF
  File "/Users/tom/miniconda/envs/sgkit-3.8-dev/lib/python3.8/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
  File "cyvcf2/cyvcf2.pyx", line 1, in init cyvcf2.cyvcf2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

We pin NumPy to < 1.22 (due to #812), and it looks like cyvcf2 0.30.15 (which was released fairly recently) uses a later version, hence the problem. I think we can pin cyvcf2 < 0.30.15.
